version: '3'
services:
  server:
    build: server
    restart: on-failure
    volumes:
      - ./server:/app
    ports:
      - 8000:8000
  frontend:
    build: frontend
    depends_on:
      - server
    environment:
      - REACT_APP_SERVER_HOST=http://localhost:8000
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
