version: '3'
services:
  server:
    build: dynwalker/server
    restart: on-failure
    volumes:
      - ./dynwalker/server:/app
    ports:
      - 8000:8000
  frontend:
    build: dynwalker/frontend
    depends_on:
      - server
    environment:
      - REACT_APP_SERVER_HOST=http://localhost:8000
    volumes:
      - ./dynwalker/frontend:/app
    ports:
      - 3000:3000
