version: '3'
services:
  server:
    build:
      dockerfile: ./server/Dockerfile
      context: dynwalker
    restart: on-failure
    volumes:
      - ./dynwalker/server:/app
      - ./dynwalker/backends:/backends
      - ./dynwalker/config.ini:/config.ini
    ports:
      - 8000:8000
  frontend:
    build: dynwalker/frontend
    depends_on:
      - server
    environment:
      - REACT_APP_SERVER_HOST=http://localhost:8000
    volumes:
      - ./dynwalker/frontend:/app
    ports:
      - 3000:3000
